# Generated by Django 4.1.6 on 2023-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ("last_name", "first_name"),
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("title",),
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ("inv_nom",),
                "verbose_name": "Экземпляр книги",
                "verbose_name_plural": "Экземпляры книги",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("name",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ("name",),
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ("name",),
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
    ]
